# Generated by Django 2.0.5 on 2019-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(blank=True, max_length=20)),
                ('p2', models.CharField(blank=True, max_length=20)),
                ('p3', models.CharField(blank=True, max_length=20)),
                ('p4', models.CharField(blank=True, max_length=20)),
                ('p5', models.IntegerField(blank=True)),
                ('p6', models.DateTimeField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': '测试插入',
                'ordering': ['-p1'],
            },
        ),
    ]
