# Generated by Django 2.0.5 on 2019-03-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('app_name', models.CharField(max_length=100)),
                ('createby', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目名称',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='machineinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=30)),
                ('m_name', models.CharField(max_length=50)),
                ('sys', models.CharField(choices=[('android', 'Android'), ('ios', 'IOS'), ('windows', 'Windows')], default='Android', max_length=20)),
                ('sysverson', models.CharField(max_length=15)),
                ('createby', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '手机名称',
                'verbose_name_plural': '手机名称',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='serverinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_sys', models.CharField(max_length=20)),
                ('serverIP', models.CharField(max_length=30)),
                ('createby', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '服务器IP',
                'verbose_name_plural': '服务器IP',
                'ordering': ['-c_time'],
            },
        ),
    ]
