# Generated by Django 2.0.5 on 2019-03-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinfo',
            options={'ordering': ['-c_time'], 'verbose_name': 'APP信息', 'verbose_name_plural': 'APP信息'},
        ),
        migrations.AlterModelOptions(
            name='machineinfo',
            options={'ordering': ['-c_time'], 'verbose_name': '手机信息', 'verbose_name_plural': '手机信息'},
        ),
        migrations.RemoveField(
            model_name='appinfo',
            name='app_name',
        ),
        migrations.AddField(
            model_name='appinfo',
            name='package',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='createby',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='pro_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='createby',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='m_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='phone_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='status',
            field=models.CharField(blank=True, default='已启用', max_length=10),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='sys',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'IOS'), ('windows', 'Windows')], default='Android', max_length=20),
        ),
        migrations.AlterField(
            model_name='machineinfo',
            name='sysverson',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='createby',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='serverIP',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='wind_sys',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
