# Generated by Django 2.0.5 on 2019-03-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project_base', '0002_auto_20190322_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='uid',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='machineinfo',
            name='uid',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='uid',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
