# Generated by Django 2.0.5 on 2019-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='runRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proName', models.CharField(blank=True, max_length=20)),
                ('caseTotal', models.CharField(blank=True, max_length=6)),
                ('caseRan', models.CharField(blank=True, max_length=10)),
                ('runTimes', models.CharField(blank=True, max_length=5)),
                ('passed', models.CharField(blank=True, max_length=5)),
                ('failed', models.CharField(blank=True, max_length=5)),
                ('jump', models.CharField(blank=True, max_length=5)),
                ('CoverageRate', models.CharField(blank=True, max_length=5)),
                ('passRate', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': '运行记录',
                'verbose_name_plural': '运行记录',
                'ordering': ['-proName'],
            },
        ),
    ]
