# Generated by Django 2.0.5 on 2019-03-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrecord',
            name='jump',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
