# Generated by Django 2.0.5 on 2019-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=10)),
                ('pro_name', models.CharField(blank=True, max_length=50)),
                ('package', models.CharField(blank=True, max_length=100)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('createby', models.CharField(blank=True, max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='启用', max_length=10)),
            ],
            options={
                'verbose_name': 'APP信息',
                'verbose_name_plural': 'APP信息',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='machineinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=10)),
                ('phone_name', models.CharField(blank=True, max_length=30)),
                ('m_name', models.CharField(blank=True, max_length=50)),
                ('sys', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'IOS'), ('windows', 'Windows')], default='Android', max_length=20)),
                ('sysverson', models.CharField(blank=True, max_length=15)),
                ('createby', models.CharField(blank=True, max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='启用', max_length=10)),
            ],
            options={
                'verbose_name': '手机信息',
                'verbose_name_plural': '手机信息',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='serverinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=10)),
                ('os', models.CharField(blank=True, max_length=20)),
                ('serverIP', models.CharField(blank=True, max_length=30)),
                ('createby', models.CharField(blank=True, max_length=20)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='启用', max_length=10)),
            ],
            options={
                'verbose_name': '服务器IP',
                'verbose_name_plural': '服务器IP',
                'ordering': ['-c_time'],
            },
        ),
    ]
